# Generated by Django 4.2.30 on 2026-05-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('user', 'Usuário'), ('viewer', 'Visualizador')], default='user', help_text='Define o nível de acesso do usuário.', max_length=10),
        ),
    ]
