# Generated by Django 4.2.30 on 2026-05-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, default='', help_text='Nome do negócio/empresa (preenchido pelo MEI no cadastro).', max_length=150),
        ),
    ]
