# Generated by Django 4.2.30 on 2026-05-09 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('related_type', models.CharField(blank=True, max_length=50)),
                ('related_id', models.BigIntegerField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='analytics_e_created_659b3f_idx'), models.Index(fields=['event_type', '-created_at'], name='analytics_e_event_t_a1a31c_idx'), models.Index(fields=['category'], name='analytics_e_categor_003499_idx')],
            },
        ),
    ]
